addSbtPlugin("org.scala-js"                % "sbt-scalajs"   % "1.18.2")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta44")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"  % "2.5.4")
addSbtPlugin("de.heikoseeberger"           % "sbt-header"    % "5.10.0")
addSbtPlugin("org.typelevel"               % "sbt-tpolecat"  % "0.5.2")
addSbtPlugin("io.spray"                    % "sbt-revolver"  % "0.10.0")
addSbtPlugin("com.github.sbt"              % "sbt-dynver"    % "5.1.0")
